[pytest]
addopts = -s -v
markers =
    ui: Маркировака для UI тестов
    slow: Маркировака для медленных тестов
    smoke: Маркировака для смок тестов
    regression: Маркировака для регрессионных тестов
    registration: Маркировка для тестов, связанных с регистрацией пользователей.
    authorization: Маркировка для тестов, связанных с авторизацией пользователей.
    courses: Маркировка для тестов, связанных с курсами.
    dashboard: Маркировка для тестов, связанных с рабочей панелью.